- name: Deploy app to Kubernetes
  hosts: localhost
  tasks:
    - name: Apply deployment
      ansible.builtin.command:
        cmd: kubectl apply -f "{{ playbook_dir }}/../kubernetes/deployment.yaml" --validate=false
    - name: Apply service
      ansible.builtin.command:
        cmd: kubectl apply -f "{{ playbook_dir }}/../kubernetes/service.yaml" --validate=false

